# Generated by Django 5.0.6 on 2026-08-23 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('LOGIN_FAILED', 'Échec connexion'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('FREQUENCY_CHANGE', 'Changement fréquence'), ('ASSIGNATION_TICKET', 'Assignation ticket'), ('TICKET_RESOLU', 'Ticket résolu'), ('TICKET_CLOTURE', 'Ticket clôturé'), ('USER_CREATED', 'Utilisateur créé'), ('PERMISSION_CHANGED', 'Changement de permission')], max_length=50, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('ancienne_valeur', models.JSONField(blank=True, null=True, verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True, verbose_name='Nouvelle valeur')),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endpoint API')),
                ('methode_http', models.CharField(blank=True, max_length=10, null=True, verbose_name='Méthode HTTP')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name="Type d'objet")),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_audit', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'Audit",
                'verbose_name_plural': "Journaux d'Audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['action', 'utilisateur'], name='audit_audit_action_98c236_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx')],
            },
        ),
    ]
