# Generated by Django 5.0.6 on 2026-08-23 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_ticket', models.CharField(choices=[('PREVENTIVE', 'Maintenance Préventive'), ('CORRECTIVE', 'Maintenance Corrective'), ('URGENCE', 'Intervention Urgence')], max_length=20, verbose_name='Type')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('CREE', 'Créé'), ('ASSIGNE', 'Assigné'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu'), ('CLOTURE', 'Clôturé')], default='CREE', max_length=20, verbose_name='Statut')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID équipement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('rapport_intervention', models.TextField(blank=True, null=True, verbose_name="Rapport d'intervention")),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type équipement')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Ticket de Maintenance',
                'verbose_name_plural': 'Tickets de Maintenance',
                'ordering': ['-priorite', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=300, verbose_name='Libellé')),
                ('est_effectue', models.BooleanField(default=False, verbose_name='Effectué')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='tickets.maintenanceticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Item Checklist',
                'verbose_name_plural': 'Items Checklist',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('ASSIGNATION', 'Assignation'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('COMMENTAIRE', 'Commentaire')], max_length=50, verbose_name='Action')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('ancienne_valeur', models.TextField(blank=True, null=True, verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.TextField(blank=True, null=True, verbose_name='Nouvelle valeur')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='tickets.maintenanceticket', verbose_name='Ticket')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique Ticket',
                'verbose_name_plural': 'Historiques Ticket',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['statut', 'priorite'], name='tickets_mai_statut_2e6b07_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['content_type', 'object_id'], name='tickets_mai_content_3f7ca7_idx'),
        ),
    ]
